#!/usr/bin/env bash
# This script transfers a file from our client to the server

if [ $# -lt 4 ]
then
	echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
	exit 1
fi

# Assigning parameters to variables

PATH_TO_FILES=$1
IP=$2
USERNAME=$3
PATH_TO_SSH_KEY=$4

# disable strict hostkey checking when using scp

scp -o "StrictHostKeyChecking no" -i "$PATH_TO_SSH_KEY" "$PATH_TO_FILES" "$USERNAME@IP:~/"

# Checking for success or failure

if [ $? -eq 0 ]
then
	echo "FILE TRANSFER SUCCESSFUL"
else
	echo "FLE TRANSFER FAILED"
fi
